# Generated by Django 4.2.1 on 2023-05-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device", models.IntegerField(default=0)),
                ("image", models.ImageField(upload_to="image/")),
                ("conf", models.FloatField(default=0.0)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
